/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.geriatrico1.vista;

import java.awt.Color;

/**
 *
 * @author Santiago
 */
public class Dashboard_Enfermero extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard_Enfermero.class.getName());

    /**
     * Creates new form Dashboard_Enfermero
     */
    public Dashboard_Enfermero(String nombreUsuario) {
        initComponents();
        
        lblUsuarioActivo.setText("Enfermer@: " + nombreUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUsuarioActivo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelCentral = new javax.swing.JPanel();
        panel_paciente2 = new com.mycompany.geriatrico1.vista.panel_paciente();
        panel_inicio1 = new com.mycompany.geriatrico1.vista.panel_inicio();
        jPanel3 = new javax.swing.JPanel();
        btnIniEnfer = new javax.swing.JButton();
        btnPaciEnfer = new javax.swing.JButton();
        btnPendEnfer = new javax.swing.JButton();
        btnReporEnfer = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(238, 242, 246));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logo_tiny.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 150));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 75));

        jLabel2.setFont(new java.awt.Font("Sans Serif Collection", 1, 48)); // NOI18N
        jLabel2.setText("DASHBOARD ENFERMERO");

        lblUsuarioActivo.setText("Usuario:");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/i-inpatient.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUsuarioActivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(134, 134, 134))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUsuarioActivo)))
                        .addContainerGap())))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        panelCentral.setLayout(new java.awt.CardLayout());
        panelCentral.add(panel_paciente2, "card2");
        panelCentral.add(panel_inicio1, "card3");

        getContentPane().add(panelCentral, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(0, 128, 128));

        btnIniEnfer.setBackground(new java.awt.Color(24, 76, 74));
        btnIniEnfer.setForeground(new java.awt.Color(255, 255, 255));
        btnIniEnfer.setText("Inicio");
        btnIniEnfer.setPreferredSize(new java.awt.Dimension(400, 150));
        btnIniEnfer.addActionListener(this::btnIniEnferActionPerformed);

        btnPaciEnfer.setBackground(new java.awt.Color(24, 76, 74));
        btnPaciEnfer.setForeground(new java.awt.Color(255, 255, 255));
        btnPaciEnfer.setText("Paciente");
        btnPaciEnfer.setPreferredSize(new java.awt.Dimension(400, 150));
        btnPaciEnfer.addActionListener(this::btnPaciEnferActionPerformed);

        btnPendEnfer.setBackground(new java.awt.Color(24, 76, 74));
        btnPendEnfer.setForeground(new java.awt.Color(255, 255, 255));
        btnPendEnfer.setText("(Pendiente)");
        btnPendEnfer.setPreferredSize(new java.awt.Dimension(400, 150));
        btnPendEnfer.addActionListener(this::btnPendEnferActionPerformed);

        btnReporEnfer.setBackground(new java.awt.Color(24, 76, 74));
        btnReporEnfer.setForeground(new java.awt.Color(255, 255, 255));
        btnReporEnfer.setText("Reporte");
        btnReporEnfer.setPreferredSize(new java.awt.Dimension(400, 150));
        btnReporEnfer.addActionListener(this::btnReporEnferActionPerformed);

        jButton1.setBackground(new java.awt.Color(24, 76, 74));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SALIR");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnReporEnfer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(btnPendEnfer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnPaciEnfer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnIniEnfer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jButton1)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnIniEnfer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btnPaciEnfer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btnPendEnfer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btnReporEnfer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(50, 50, 50))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniEnferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniEnferActionPerformed
       panel_paciente2.setVisible(false);
       panel_inicio1.setVisible(true);
        seleccionarBoton( btnIniEnfer);
    }//GEN-LAST:event_btnIniEnferActionPerformed

    private void btnPaciEnferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaciEnferActionPerformed
       panel_paciente2.setVisible(true);
       panel_inicio1.setVisible(false);
        seleccionarBoton(btnPaciEnfer);
    }//GEN-LAST:event_btnPaciEnferActionPerformed

     public void seleccionarBoton(javax.swing.JButton botonseleccionado){
        javax.swing.JButton[] botones={btnIniEnfer,btnPaciEnfer,btnPendEnfer, btnReporEnfer};
        
        for(javax.swing.JButton btn:botones){
            if(btn==botonseleccionado){
                btn.setBackground(new Color(51,153,153));
            }else{
                btn.setBackground(null);
            }
            
        }
    }
    
    
    
    
    private void btnPendEnferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendEnferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPendEnferActionPerformed

    private void btnReporEnferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporEnferActionPerformed
        // TODO add your handling code here:
        seleccionarBoton(btnReporEnfer);
    }//GEN-LAST:event_btnReporEnferActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        Dash_login lg = new Dash_login();
        lg.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniEnfer;
    private javax.swing.JButton btnPaciEnfer;
    private javax.swing.JButton btnPendEnfer;
    private javax.swing.JButton btnReporEnfer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblUsuarioActivo;
    public javax.swing.JPanel panelCentral;
    public com.mycompany.geriatrico1.vista.panel_inicio panel_inicio1;
    public com.mycompany.geriatrico1.vista.panel_paciente panel_paciente2;
    // End of variables declaration//GEN-END:variables
}
