package com.mycompany.geriatrico1.vista;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mary
 */
public class Dashboard_Medico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard_Medico.class.getName());

    /**
     * Creates new form Medico
     */
    public Dashboard_Medico(String nombreUsuario) {
        initComponents();
        
        lblUsuario_Med.setText(nombreUsuario);
        //IMAGENES EN AWT
        ImageIcon iconoAlerta=new ImageIcon("C:\\ProyectoIntegrador\\GeriatricoJava\\src\\main\\resources\\Recursos\\alerta.jpg");
        Image imagenAlerta=iconoAlerta.getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH);
        btnAlerta.setIcon(new ImageIcon(imagenAlerta));
        
        ImageIcon iconoHistorial=new ImageIcon("C:\\ProyectoIntegrador\\GeriatricoJava\\src\\main\\resources\\Recursos\\hiatorial.jpg");
        Image imagenHistorial=iconoHistorial.getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH);
        btnHistorial.setIcon(new ImageIcon(imagenHistorial));
        
        ImageIcon iconoActualizar=new ImageIcon("C:\\ProyectoIntegrador\\GeriatricoJava\\src\\main\\resources\\Recursos\\Actualizar.png");
        Image imagenActualizar=iconoActualizar.getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH);
        
        ImageIcon iconoTratamiento=new ImageIcon("C:\\ProyectoIntegrador\\GeriatricoJava\\src\\main\\resources\\Recursos\\tratamiento.png");
        Image imagenTratamiento=iconoTratamiento.getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH);
        btnTratamiento.setIcon(new ImageIcon(imagenTratamiento));
        
        //PANELES INTERACTIVOS
        PanelAlertas.setVisible(true);
        panel.setVisible(false);
        PanelHistorial.setVisible(false);
        PanelGenerar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMenu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnAlerta = new javax.swing.JButton();
        lblUsuario_Med = new javax.swing.JLabel();
        lblEspecialidad = new javax.swing.JLabel();
        btnHistorial = new javax.swing.JButton();
        btnTratamiento = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPacientesActivos = new javax.swing.JTable();
        PanelContenido = new javax.swing.JPanel();
        PanelAlertas = new javax.swing.JPanel();
        panelAlerta1 = new javax.swing.JPanel();
        lblNombrePaciente1 = new javax.swing.JLabel();
        lblHora1 = new javax.swing.JLabel();
        lblObservacion1 = new javax.swing.JLabel();
        btnAtender1 = new javax.swing.JButton();
        panelAlerta2 = new javax.swing.JPanel();
        lblNombrePaciente2 = new javax.swing.JLabel();
        lblObservacion2 = new javax.swing.JLabel();
        lblHora2 = new javax.swing.JLabel();
        btnAtender2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        panelAlerta3 = new javax.swing.JPanel();
        btnAtender3 = new javax.swing.JButton();
        lblNombrePaciente3 = new javax.swing.JLabel();
        lblObservacion3 = new javax.swing.JLabel();
        lblHora3 = new javax.swing.JLabel();
        btnCargarAlertas = new javax.swing.JButton();
        PanelHistorial = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaAntecedentes = new javax.swing.JTable();
        NuevaConsulta = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtDiagnosticoAntecedentes = new javax.swing.JTextPane();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtObservacionesAntecedentes = new javax.swing.JTextPane();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPacientesHistorial = new javax.swing.JTable();
        jLabel34 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDiagnostico = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextPane();
        btnGuardarHistorial = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        txtBusquedaPAciente = new javax.swing.JTextField();
        txtTemp = new javax.swing.JTextField();
        txtFrec = new javax.swing.JTextField();
        txtPresionSis = new javax.swing.JTextField();
        txtPresionDias = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        PanelGenerar = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnGenerarTratamiento = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        dateInicioTrata = new com.toedter.calendar.JDateChooser();
        dateFinTrata = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        cmbFrecuencia = new javax.swing.JComboBox<>();
        txtDosisMed = new javax.swing.JTextField();
        txtCantidadMed = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtObservacionesReceta = new javax.swing.JTextArea();
        cmbNombreMedicamento = new javax.swing.JComboBox<>();
        cmbDuracion = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        txtPaciente = new javax.swing.JTextField();
        cmbNombreTratamiento = new javax.swing.JComboBox<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtObservacionesTratamiento = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        lblUsuarioActivo = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblSeccion = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 247, 250));

        PanelMenu.setBackground(new java.awt.Color(0, 128, 128));
        PanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(24, 76, 74));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SALIR");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        PanelMenu.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 730, -1, -1));

        btnAlerta.setBackground(new java.awt.Color(24, 76, 74));
        btnAlerta.setForeground(new java.awt.Color(255, 255, 255));
        btnAlerta.setText("Alertas de Pacientes");
        btnAlerta.addActionListener(this::btnAlertaActionPerformed);
        PanelMenu.add(btnAlerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 190, -1));

        lblUsuario_Med.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsuario_Med.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario_Med.setText("Dr. Marisol Herrera");
        PanelMenu.add(lblUsuario_Med, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lblEspecialidad.setForeground(new java.awt.Color(255, 255, 255));
        lblEspecialidad.setText("Cardiologa");
        PanelMenu.add(lblEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        btnHistorial.setBackground(new java.awt.Color(24, 76, 74));
        btnHistorial.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorial.setText("Historial Clinico");
        btnHistorial.addActionListener(this::btnHistorialActionPerformed);
        PanelMenu.add(btnHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 190, -1));

        btnTratamiento.setBackground(new java.awt.Color(24, 76, 74));
        btnTratamiento.setForeground(new java.awt.Color(255, 255, 255));
        btnTratamiento.setText("Generar Tratamiento");
        btnTratamiento.addActionListener(this::btnTratamientoActionPerformed);
        PanelMenu.add(btnTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 190, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Pacientes activos");
        PanelMenu.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        txtBuscar.setText("Buscar");
        txtBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarFocusLost(evt);
            }
        });
        txtBuscar.addActionListener(this::txtBuscarActionPerformed);
        PanelMenu.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 160, -1));

        tablaPacientesActivos.setBackground(new java.awt.Color(245, 247, 250));
        tablaPacientesActivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cedula", "Nombre"
            }
        ));
        jScrollPane1.setViewportView(tablaPacientesActivos);

        PanelMenu.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 170, 200));

        PanelContenido.setBackground(new java.awt.Color(245, 247, 250));

        PanelAlertas.setBackground(new java.awt.Color(245, 247, 250));
        PanelAlertas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAlerta1.setBackground(new java.awt.Color(255, 255, 255));
        panelAlerta1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.red, null, null));

        lblNombrePaciente1.setText("Elena Vazquez");

        lblHora1.setText("Hoy 10:24");

        lblObservacion1.setText("Paciente reporta frecuencia cardiaca elevada(135) reportada por monitor");

        btnAtender1.setText("Atender");
        btnAtender1.addActionListener(this::btnAtender1ActionPerformed);

        javax.swing.GroupLayout panelAlerta1Layout = new javax.swing.GroupLayout(panelAlerta1);
        panelAlerta1.setLayout(panelAlerta1Layout);
        panelAlerta1Layout.setHorizontalGroup(
            panelAlerta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlerta1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelAlerta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlerta1Layout.createSequentialGroup()
                        .addComponent(lblHora1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelAlerta1Layout.createSequentialGroup()
                        .addComponent(lblNombrePaciente1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelAlerta1Layout.createSequentialGroup()
                        .addComponent(lblObservacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                        .addComponent(btnAtender1)
                        .addGap(17, 17, 17))))
        );
        panelAlerta1Layout.setVerticalGroup(
            panelAlerta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlerta1Layout.createSequentialGroup()
                .addComponent(lblNombrePaciente1)
                .addGap(15, 15, 15)
                .addGroup(panelAlerta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblObservacion1)
                    .addComponent(btnAtender1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHora1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        PanelAlertas.add(panelAlerta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 660, -1));

        panelAlerta2.setBackground(new java.awt.Color(255, 255, 255));
        panelAlerta2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.orange, null, null));

        lblNombrePaciente2.setText("Juan Rios");

        lblObservacion2.setText("Paciente reporta dolor toraxico leve al esfuerzo");

        lblHora2.setText("Hoy 8:47");

        btnAtender2.setText("Atender");
        btnAtender2.addActionListener(this::btnAtender2ActionPerformed);

        javax.swing.GroupLayout panelAlerta2Layout = new javax.swing.GroupLayout(panelAlerta2);
        panelAlerta2.setLayout(panelAlerta2Layout);
        panelAlerta2Layout.setHorizontalGroup(
            panelAlerta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlerta2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelAlerta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlerta2Layout.createSequentialGroup()
                        .addGroup(panelAlerta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHora2)
                            .addComponent(lblNombrePaciente2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelAlerta2Layout.createSequentialGroup()
                        .addComponent(lblObservacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                        .addComponent(btnAtender2)
                        .addGap(16, 16, 16))))
        );
        panelAlerta2Layout.setVerticalGroup(
            panelAlerta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlerta2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombrePaciente2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAlerta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblObservacion2)
                    .addComponent(btnAtender2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHora2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        PanelAlertas.add(panelAlerta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 660, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Alertas generadas automaticamente por signos vitales o reportadas por el paciente ordenadas por urgencia");
        PanelAlertas.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 7, -1, -1));

        panelAlerta3.setBackground(new java.awt.Color(255, 255, 255));
        panelAlerta3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 255, 102), null, null));

        btnAtender3.setText("Atender");
        btnAtender3.addActionListener(this::btnAtender3ActionPerformed);

        lblNombrePaciente3.setText("Juan Rios");

        lblObservacion3.setText("  ");

        lblHora3.setText("Juan Rios");

        javax.swing.GroupLayout panelAlerta3Layout = new javax.swing.GroupLayout(panelAlerta3);
        panelAlerta3.setLayout(panelAlerta3Layout);
        panelAlerta3Layout.setHorizontalGroup(
            panelAlerta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlerta3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAlerta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblObservacion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHora3, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                    .addComponent(lblNombrePaciente3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(btnAtender3)
                .addGap(15, 15, 15))
        );
        panelAlerta3Layout.setVerticalGroup(
            panelAlerta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlerta3Layout.createSequentialGroup()
                .addGroup(panelAlerta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlerta3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnAtender3))
                    .addGroup(panelAlerta3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblNombrePaciente3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblObservacion3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHora3)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        PanelAlertas.add(panelAlerta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 660, -1));

        btnCargarAlertas.setText("Cargar ALERTAS");
        PanelAlertas.add(btnCargarAlertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 150, -1));

        PanelHistorial.setBackground(new java.awt.Color(245, 247, 250));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Selecciona un paciente para revisar su linea de tiempo clinica, consultas, diagnosticos y tratamientos previos");

        tablaAntecedentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Hora", "Peso", "Presion", "Temperatura", "Frecuencia ", "Estado"
            }
        ));
        jScrollPane3.setViewportView(tablaAntecedentes);

        NuevaConsulta.setText("Nueva consulta");
        NuevaConsulta.addActionListener(this::NuevaConsultaActionPerformed);

        jScrollPane6.setViewportView(txtDiagnosticoAntecedentes);

        jLabel24.setText("Diagnostico");

        jLabel25.setText("Observaciones");

        jScrollPane7.setViewportView(txtObservacionesAntecedentes);

        jLabel26.setText("Antecedentes");

        tablaPacientesHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cedula", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaPacientesHistorial);

        jLabel34.setText("Pacientes");

        javax.swing.GroupLayout PanelHistorialLayout = new javax.swing.GroupLayout(PanelHistorial);
        PanelHistorial.setLayout(PanelHistorialLayout);
        PanelHistorialLayout.setHorizontalGroup(
            PanelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHistorialLayout.createSequentialGroup()
                .addGroup(PanelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(PanelHistorialLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(PanelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelHistorialLayout.createSequentialGroup()
                                .addGroup(PanelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelHistorialLayout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel34))
                                    .addComponent(jLabel24))
                                .addGap(273, 273, 273)
                                .addComponent(jLabel25))
                            .addComponent(jLabel26)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelHistorialLayout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NuevaConsulta))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelHistorialLayout.setVerticalGroup(
            PanelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHistorialLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(PanelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NuevaConsulta)
                .addGap(496, 496, 496))
        );

        panel.setBackground(new java.awt.Color(245, 247, 250));

        jLabel7.setText("Paciente");

        jLabel9.setText("Motivo de consulta");

        txtMotivo.addActionListener(this::txtMotivoActionPerformed);

        jLabel10.setText("Observaciones");

        jLabel11.setText("Diagnostico");

        txtDiagnostico.addActionListener(this::txtDiagnosticoActionPerformed);

        jScrollPane4.setViewportView(txtObservaciones);

        btnGuardarHistorial.setText("Guardar en Historial");
        btnGuardarHistorial.addActionListener(this::btnGuardarHistorialActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Registra una nueva entrada en la historia clinica del paciente tras la consulta");

        jLabel59.setText("Peso");

        jLabel60.setText("Presion");

        jLabel61.setText("Temperatura");

        jLabel62.setText("Frecuencia Cardiaca");

        txtPeso.addActionListener(this::txtPesoActionPerformed);

        txtBusquedaPAciente.addActionListener(this::txtBusquedaPAcienteActionPerformed);

        txtTemp.setText(" ");
        txtTemp.addActionListener(this::txtTempActionPerformed);

        txtPresionDias.addActionListener(this::txtPresionDiasActionPerformed);

        jLabel1.setText("<html><H2>/</H2>");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(txtDiagnostico, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                        .addContainerGap(659, Short.MAX_VALUE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(txtBusquedaPAciente, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(66, 66, 66)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel60)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addComponent(txtPresionSis, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPresionDias, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel9)
                            .addComponent(txtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7)
                            .addComponent(btnGuardarHistorial))
                        .addGap(67, 67, 67)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel61, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTemp))
                                .addGap(48, 48, 48)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel62)
                                    .addComponent(txtFrec, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(3, 3, 3)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBusquedaPAciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(45, 45, 45))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel59)
                                    .addComponent(jLabel60))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPresionSis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPresionDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel61)
                                    .addComponent(jLabel62))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFrec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)))
                        .addGap(74, 74, 74)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMotivo)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnGuardarHistorial)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelGenerar.setBackground(new java.awt.Color(245, 247, 250));

        jLabel12.setText("Paciente");

        jLabel13.setText("Nombre del Tratamiento");

        jLabel14.setText("Observaciones");

        jLabel16.setText("Fecha de inicio");

        jLabel17.setText("Fecha de fin");

        btnGenerarTratamiento.setText("Generar Tratamiento");

        jLabel19.setText("Genera un plan de tratamiento a partir del diagnostico actual del paciente.");

        jPanel5.setBackground(new java.awt.Color(245, 247, 250));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));

        jLabel36.setText("Cantidad");

        jLabel37.setText("Dosis");

        jLabel38.setText("Frecuencia");

        jLabel39.setText("Duracion");

        jLabel42.setText("Nombre Medicamento");

        jLabel49.setText("Observaciones");

        cmbFrecuencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione uno...", "Cada 6 horas", "Cada 8 horas", "Cada 12 horas", "Cada 24 horas (1 vez al día)", "Según necesidad" }));

        txtCantidadMed.addActionListener(this::txtCantidadMedActionPerformed);

        txtObservacionesReceta.setColumns(20);
        txtObservacionesReceta.setRows(5);
        jScrollPane5.setViewportView(txtObservacionesReceta);

        cmbDuracion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione uno...", "3   días", "5   días", "7   días", "10 días", "15 días", "30 días", "Continuo / Permanente" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addGap(26, 26, 26)
                        .addComponent(cmbNombreMedicamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCantidadMed, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDosisMed, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbFrecuencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbDuracion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53)))
                .addContainerGap(1243, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(cmbNombreMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(txtCantidadMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel37))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39)
                            .addComponent(txtDosisMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel49)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jLabel18.setText("Receta");

        txtObservacionesTratamiento.setColumns(20);
        txtObservacionesTratamiento.setRows(5);
        jScrollPane8.setViewportView(txtObservacionesTratamiento);

        javax.swing.GroupLayout PanelGenerarLayout = new javax.swing.GroupLayout(PanelGenerar);
        PanelGenerar.setLayout(PanelGenerarLayout);
        PanelGenerarLayout.setHorizontalGroup(
            PanelGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGenerarLayout.createSequentialGroup()
                .addGroup(PanelGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGenerarLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(PanelGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelGenerarLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(txtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14)
                            .addComponent(jLabel18)
                            .addGroup(PanelGenerarLayout.createSequentialGroup()
                                .addGroup(PanelGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbNombreTratamiento, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(62, 62, 62)
                                .addGroup(PanelGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(dateInicioTrata, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(PanelGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dateFinTrata, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelGenerarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19))
                    .addGroup(PanelGenerarLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnGenerarTratamiento)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelGenerarLayout.setVerticalGroup(
            PanelGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGenerarLayout.createSequentialGroup()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(PanelGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGenerarLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(6, 6, 6)
                        .addComponent(cmbNombreTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14))
                    .addGroup(PanelGenerarLayout.createSequentialGroup()
                        .addGroup(PanelGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateFinTrata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateInicioTrata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnGenerarTratamiento)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelContenidoLayout = new javax.swing.GroupLayout(PanelContenido);
        PanelContenido.setLayout(PanelContenidoLayout);
        PanelContenidoLayout.setHorizontalGroup(
            PanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(PanelHistorial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelAlertas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1403, Short.MAX_VALUE))
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelContenidoLayout.setVerticalGroup(
            PanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelAlertas, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel6.setBackground(new java.awt.Color(238, 242, 246));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logo_tiny.png"))); // NOI18N
        jLabel50.setMaximumSize(new java.awt.Dimension(200, 150));
        jLabel50.setMinimumSize(new java.awt.Dimension(100, 75));

        lblUsuarioActivo.setText("Usuario:");

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/i-inpatient.png"))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("ALERTAS DE PACIENTES");

        lblSeccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSeccion.setText("<html> <H1>  DASHBOARD MEDICO  </H1>");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("Pacientes hoy");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("Sin atender");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("12");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("20");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuarioActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70)
                .addComponent(jLabel52)
                .addGap(29, 29, 29))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblUsuarioActivo)
                                .addGap(25, 25, 25)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 1945, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 1954, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        // TODO add your handling code here:
        lblSeccion.setText("EXPEDIENTE");
        lblTitulo.setText("HISTORIAL CLINICO");
        
        seleccionarBoton(btnHistorial);
        
        PanelHistorial.setVisible(true);
        PanelAlertas.setVisible(false);
        panel.setVisible(false);
        PanelGenerar.setVisible(false);
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTratamientoActionPerformed
        // TODO add your handling code here:
        lblSeccion.setText("EXPEDIENTE");
        lblTitulo.setText("GENERAR TRATAMIENTO");
        
        seleccionarBoton(btnTratamiento);
        
        PanelGenerar.setVisible(true);
        panel.setVisible(false);
        PanelAlertas.setVisible(false);
        PanelHistorial.setVisible(false);
    }//GEN-LAST:event_btnTratamientoActionPerformed

    private void btnAlertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlertaActionPerformed
        // TODO add your handling code here:
        lblSeccion.setText("DASHBOARD MEDICO");
        lblTitulo.setText("ALERTAS DE PACIENTES");
        
        seleccionarBoton(btnAlerta);
        
        PanelAlertas.setVisible(true);
        PanelHistorial.setVisible(false);
        panel.setVisible(false);
        PanelGenerar.setVisible(false);
    }//GEN-LAST:event_btnAlertaActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFocusGained
        // TODO add your handling code here:
        if(txtBuscar.getText().equals("Buscar")){
            txtBuscar.setText("");
            txtBuscar.setForeground(java.awt.Color.black);
        }
    }//GEN-LAST:event_txtBuscarFocusGained

    private void txtBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFocusLost
        // TODO add your handling code here:
        if(txtBuscar.getText().trim().isEmpty()){
            txtBuscar.setText("Buscar");
            txtBuscar.setForeground(java.awt.Color.gray);
        }
    }//GEN-LAST:event_txtBuscarFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();

        Dash_login lg = new Dash_login();
        lg.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoActionPerformed

    private void btnGuardarHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarHistorialActionPerformed
        // TODO add your handling code here:
        seleccionarBoton(btnGuardarHistorial);

        panel.setVisible(false);
        PanelAlertas.setVisible(false);
        PanelHistorial.setVisible(true);
        PanelGenerar.setVisible(false);
    }//GEN-LAST:event_btnGuardarHistorialActionPerformed

    private void txtDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiagnosticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiagnosticoActionPerformed

    private void txtMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMotivoActionPerformed

    private void NuevaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaConsultaActionPerformed
        /*/ TODO add your handling code here:
        seleccionarBoton(NuevaConsulta);
        panel.setVisible(true);

        PanelAlertas.setVisible(false);
        PanelHistorial.setVisible(false);
        PanelGenerar.setVisible(false);
        */
    }//GEN-LAST:event_NuevaConsultaActionPerformed

    private void btnAtender3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtender3ActionPerformed
        // TODO add your handling code here:
        btnAtender3.setText("Atendido");
    }//GEN-LAST:event_btnAtender3ActionPerformed

    private void btnAtender2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtender2ActionPerformed
        // TODO add your handling code here:
        btnAtender2.setText("Atendido");
    }//GEN-LAST:event_btnAtender2ActionPerformed

    private void btnAtender1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtender1ActionPerformed
        // TODO add your handling code here:
        btnAtender1.setText("Atendido");
    }//GEN-LAST:event_btnAtender1ActionPerformed

    private void txtTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempActionPerformed

    private void txtPresionDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPresionDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPresionDiasActionPerformed

    private void txtBusquedaPAcienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaPAcienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaPAcienteActionPerformed

    private void txtCantidadMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadMedActionPerformed

    public void seleccionarBoton(javax.swing.JButton botonseleccionado){
        javax.swing.JButton[] botones={btnAlerta,btnHistorial,btnTratamiento, NuevaConsulta};
        
        for(javax.swing.JButton btn:botones){
            if(btn==botonseleccionado){
                btn.setBackground(new Color(51,153,153));
            }else{
                btn.setBackground(null);
            }
            
        }
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton NuevaConsulta;
    public javax.swing.JPanel PanelAlertas;
    public javax.swing.JPanel PanelContenido;
    public javax.swing.JPanel PanelGenerar;
    public javax.swing.JPanel PanelHistorial;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JButton btnAlerta;
    public javax.swing.JButton btnAtender1;
    public javax.swing.JButton btnAtender2;
    public javax.swing.JButton btnAtender3;
    public javax.swing.JButton btnCargarAlertas;
    public javax.swing.JButton btnGenerarTratamiento;
    public javax.swing.JButton btnGuardarHistorial;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnTratamiento;
    public javax.swing.JComboBox<String> cmbDuracion;
    public javax.swing.JComboBox<String> cmbFrecuencia;
    public javax.swing.JComboBox<String> cmbNombreMedicamento;
    public javax.swing.JComboBox<String> cmbNombreTratamiento;
    public com.toedter.calendar.JDateChooser dateFinTrata;
    public com.toedter.calendar.JDateChooser dateInicioTrata;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JLabel lblEspecialidad;
    public javax.swing.JLabel lblHora1;
    public javax.swing.JLabel lblHora2;
    public javax.swing.JLabel lblHora3;
    public javax.swing.JLabel lblNombrePaciente1;
    public javax.swing.JLabel lblNombrePaciente2;
    public javax.swing.JLabel lblNombrePaciente3;
    public javax.swing.JLabel lblObservacion1;
    public javax.swing.JLabel lblObservacion2;
    public javax.swing.JLabel lblObservacion3;
    private javax.swing.JLabel lblSeccion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuarioActivo;
    public javax.swing.JLabel lblUsuario_Med;
    public javax.swing.JPanel panel;
    public javax.swing.JPanel panelAlerta1;
    public javax.swing.JPanel panelAlerta2;
    public javax.swing.JPanel panelAlerta3;
    public javax.swing.JTable tablaAntecedentes;
    public javax.swing.JTable tablaPacientesActivos;
    public javax.swing.JTable tablaPacientesHistorial;
    public javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtBusquedaPAciente;
    public javax.swing.JTextField txtCantidadMed;
    public javax.swing.JTextField txtDiagnostico;
    public javax.swing.JTextPane txtDiagnosticoAntecedentes;
    public javax.swing.JTextField txtDosisMed;
    public javax.swing.JTextField txtFrec;
    public javax.swing.JTextField txtMotivo;
    public javax.swing.JTextPane txtObservaciones;
    public javax.swing.JTextPane txtObservacionesAntecedentes;
    public javax.swing.JTextArea txtObservacionesReceta;
    public javax.swing.JTextArea txtObservacionesTratamiento;
    public javax.swing.JTextField txtPaciente;
    public javax.swing.JTextField txtPeso;
    public javax.swing.JTextField txtPresionDias;
    public javax.swing.JTextField txtPresionSis;
    public javax.swing.JTextField txtTemp;
    // End of variables declaration//GEN-END:variables
}
